version: '3.8'

services:
  myria-node:
    build: .
    container_name: myria-node
    privileged: true
    restart: unless-stopped
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - myria-data:/home/myria/.myria
    ports:
      - "8333:8333"
      - "8334:8334" 
      - "8335:8335"
    environment:
      - DEBIAN_FRONTEND=noninteractive
    healthcheck:
      test: ["CMD", "systemctl", "is-active", "myria"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  myria-data:
    driver: local
